[Solver docs] Add CIP 36 updates
cowprotocol/docs pull request #323
Opened 2024-02-07 23:14 UTC by harisang

This PR updates the solver rewards part with the latest [CIP-36](https://snapshot.org/#/cow.eth/proposal/0x4e58f9c1208121c0e06282b5541b458bc8c8b76090263e25448848f3194df986) changes, that just passed.

2024-02-08 05:45 UTC, mfw78 requested changes

2024-02-08 05:45 UTC, mfw78 commented on docs/cow-protocol/reference/core/auctions/rewards.md
> +As specified in [CIP-27](https://snapshot.org/#/cow.eth/proposal/0x64e061568e86e8d2eec344d4a892e4126172b992cabe59a0b24c51c4c7e6cc33) and [CIP-36](https://snapshot.org/#/cow.eth/proposal/0x4e58f9c1208
```suggestion
As specified in [CIP-27](https://snapshot.org/#/cow.eth/proposal/0x64e061568e86e8d2eec344d4a892e4126172b992cabe59a0b24c51c4c7e6cc33) and [CIP-36](https://snapshot.org/#/cow.eth/proposal/0x4e58f9c1208121c0e06282b5541b458bc8c8b76090263e25448848f3194df986), solvers that participate in the price estimation competition get rewarded as follows. Each order that is within market price, is associated with a quote that was computed as part of the price estimation competition, and was used in order to compute the limit price of the order. The protocol keeps track of the quote associated with each created order and the corresponding solver that provided the quote, and if and when the order gets executed, the solver that provided the quote (that can be different compared to the solver that ended up executing the order) gets rewarded with $$min{0.0006 ETH, 6 COW}$$, where again, the conversion from ETH to COW is done by using an up-to-date price.
```

2024-02-08 05:45 UTC, mfw78 commented on docs/cow-protocol/reference/core/auctions/rewards.md
> +As specified in [CIP-27](https://snapshot.org/#/cow.eth/proposal/0x64e061568e86e8d2eec344d4a892e4126172b992cabe59a0b24c51c4c7e6cc33) and [CIP-36](https://snapshot.org/#/cow.eth/proposal/0x4e58f9c1208
Typo

2024-02-08 08:14 UTC, mfw78 approved these changes

2024-02-08 09:32 UTC, fhenneke approved these changes

2024-02-08 11:12 UTC, merged

2024-02-29 19:22 UTC, gogonimago commented
Ok I've reviewed, the grammar looks good, the one comment I have is I would remove the punctuation and spacing that occurs after variable names and equations in several places. I would simply start a new sentence under each instance of this.

<img width="1000" alt="Screenshot 2024-02-29 at 2 20 57 PM" src="https://github.com/cowprotocol/docs/assets/78171199/7aa09eba-1c55-4f80-ae7c-4102be659a12">

2024-03-25 07:26 UTC, mfw78 commented
@gogonimago Would you be able to file a supplemental PR for this? :pray: