Add CoW AMM Deployer tutorial
cowprotocol/docs pull request #336
Opened 2024-03-06 16:49 UTC by yvesfracari

# Description

Add a tutorial about the to-be-launched CoW AMM Deployer Safe App.

2024-03-06 17:29 UTC, mfw78 requested changes
Looks great overall, find some feedback in-line suggestions

2024-03-06 17:29 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +This app is only accessible from a Safe wallet. **It is recommended that the Safe wallet only be used for the purpose of deploying the CoW AMM.** Also please take note that the Safe wallet must alrea
```suggestion
This app is only accessible from a Safe wallet. 

:::caution

The Safe wallet you use to create a CoW AMM should **ONLY** be used for the purpose of deploying a CoW AMM.

:::

:::tip

Provide the tokens for the CoW AMM to your Safe wallet **before** creating the CoW AMM. Beware **any** imbalance between tokens will _automatically_ be traded.

:::
```

2024-03-06 17:29 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +Once that's done, you're ready to create your first AMM!
```suggestion
Once that's done, you're ready to create your first CoW AMM!
```

2024-03-06 17:29 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +   - **Price Oracle**: Choose the price oracle (e.g., Balancer, UniSwap V3) to provide price hints to the AMM. Enter the pool identifier used by the selected protocol. You can also load this informat
```suggestion
   - **Price Oracle**: Choose the price oracle (e.g., Balancer, UniSwap V3) to provide price hints to the watch-tower about your CoW AMM. Enter the pool identifier used by the selected protocol. You can also load this information from the protocol subgraph using the provided button. If the button fails, it means there isn't a pool with at least $1000 USD of TVL for that token pair.
```

2024-03-06 17:29 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +   - **Minimum Trade Amount**: Specify the minimum amount of the first token required for each trade. For most tokens, this value is automatically filled. If not, a good strategy is to calculate the
```suggestion
   - **Minimum Trade Amount**: Specify the minimum amount of the first token required for each trade. For most tokens, this value is automatically filled. If not, a strategy may be to calculate the equivalent of $10 USD in the first token.
```

2024-03-06 17:29 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +   - **Fallback Handler**: If your wallet is unsupported, upgrade to a Safe with the special fallback handler. [Learn all about the new Safe fallback handler](https://blog.cow.fi/all-you-need-to-know
```suggestion
   - **Fallback Handler**: If your wallet is unsupported, upgrade to a Safe with the special fallback handler. [Learn all about the new Safe Extensible Fallback Handler](https://blog.cow.fi/all-you-need-to-know-about-cow-swaps-new-safe-fallback-handler-8ef0439925d1) and its relevance to Safe in this [overview](https://help.safe.global/en/articles/40838-what-is-a-fallback-handler-and-how-does-it-relate-to-safe). Naturally, the upgrade process has undergone [extensive auditing](https://github.com/cowprotocol/composable-cow/tree/ab3addad9bc05acdbf5fb040eb5c336209b58e31/audits) for increased peace of mind.
```

2024-03-06 17:29 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +1. **Stop AMM LP Position**: Clicking this button will redirect you to a confirmation page. After confirming, the AMM will be stopped, and the tokens will remain in your Safe wallet.
```suggestion
1. **Stop AMM LP Position**: Clicking this button will redirect you to a confirmation page. After confirming, the CoW AMM will be stopped, and the tokens in your Safe wallet will no longer be used to provide liquidity.
```

2024-03-06 17:29 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +1. **Can I create multiple AMMs with the same Safe wallet?**
```suggestion
1. **Can I create multiple CoW AMMs with the same Safe wallet?**
```

2024-03-06 17:29 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +   - When you stop an AMM LP position, the tokens that were provided as liquidity will be returned to your Safe wallet. You can then withdraw or use them for other purposes.
```suggestion
   - When you stop an AMM LP position, your tokens in your Safe will no longer be used to provide liqudity. As the CoW AMM **IS** the Safe when there is an active CoW AMM, the liquidity never leaves your Safe wallet! You can then withdraw or use them for other purposes.
```

2024-03-06 17:38 UTC, yvesfracari commented
I have read the CLA Document and I hereby sign the CLA

2024-03-06 19:01 UTC, mendesfabio approved these changes

2024-03-06 19:01 UTC, mendesfabio commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +   - **Price Oracle**: Choose the price oracle (e.g., Balancer, UniSwap V3) to provide price hints to the watch-tower about your CoW AMM. Enter the pool identifier used by the selected protocol. You
```suggestion
   - **Price Oracle**: Choose the price oracle (e.g., Balancer, Uniswap V2) to provide price hints to the watch-tower about your CoW AMM. Enter the pool identifier used by the selected protocol. You can also load this information from the protocol subgraph using the provided button. If the button fails, it means there isn't a pool with at least $1000 USD of TVL for that token pair.
```

2024-03-06 19:01 UTC, mendesfabio commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +For further assistance or questions, join the [CoW Protocol Discord](https://discord.com/invite/cowprotocol) and ask in the `#tech-talk` channel.
I wonder if we should redirect to #tech-talk or #cow-amm channel

2024-03-07 06:24 UTC, mfw78 commented on docs/cow-protocol/tutorials/cow-amm-deployer.mdx
> +For further assistance or questions, join the [CoW Protocol Discord](https://discord.com/invite/cowprotocol) and ask in the `#tech-talk` channel.
From my understanding it's not possible (I don't think?) to set the invite link for discord to specific channels?

2024-03-18 16:36 UTC, mfw78 approved these changes

2024-03-18 16:36 UTC, merged